load EQUATION.maude
load ../mUnit.maude

(munit EQUATION is
		*** Veamos ahora las funciones referidas a las ecuaciones de primer grado.
	assertEqual(first-degree-equation(2.0, 1.0), - 0.5)
		*** Veamos ahora las funciones referidas a las ecuaciones de segundo grado.
	assertEqual(second-degree-equation-1(-1.0, 2.0, 3.0), -1.0)
	assertDifferent(second-degree-equation-1(-1.0, 2.0, 3.0), 3.0)
	assertEqual(second-degree-equation-2(-3.0, 2.0, 1.0), 1.0)
	assertDifferent(second-degree-equation-2(-3.0, 2.0, 1.0), -1.0 / 3.0)
	assertEqual(second-degree-equation-1(0.0, 5.0, -2.0), second-degree-equation-2(0.0, 5.0, -2.0))
	assertEqual(second-degree-equation-1(0.0, 5.0, -2.0), second-degree-equation-2(0.0, 1.0, -2.0 / 5.0))
	assertEqual(second-degree-equation-1(0.0, 5.0, -2.0), first-degree-equation(5.0, -2.0))
endu)
